
---
apiVersion: v1
kind: Namespace
metadata:
  name: test0-a
  annotations:
    field.cattle.io/projectId: c-m-gnvvtdhl:test0
  labels:
    field.cattle.io/projectId: test0
---
apiVersion: v1
kind: Namespace
metadata:
  name: test0-b
  annotations:
    field.cattle.io/projectId: c-m-gnvvtdhl:test0
  labels:
    field.cattle.io/projectId: test0
---
apiVersion: v1
kind: Secret
metadata:
  name: test0-a
  namespace: test0-a
type: Opaque
data:
  username: bWVnYV9zZWNyZXRfa2V5Cg==
  password: cmVhbGx5X3NlY3JldF92YWx1ZTEK
---
apiVersion: v1
kind: Secret
metadata:
  name: test0-b
  namespace: test0-b
type: Opaque
data:
  username: bWVnYV9zZWNyZXRfa2V5Cg==
  password: cmVhbGx5X3NlY3JldF92YWx1ZTEK
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashing-test-pod-test0
  namespace: test0-a
spec:
  selector:
    matchLabels:
      app: crashing-test-pod-test0
  replicas: 1
  template:
    metadata:
      labels:
        app: crashing-test-pod-test0
    spec:     
      containers:
        - command:
            - bash
            - -c
            - "echo test; sleep 10; exit 1;"
          image: ubuntu
          name: crashing-test-container

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
  namespace: test0-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
