

---
apiVersion: management.cattle.io/v3
description: ""
enabled: true
kind: User
metadata:
  annotations:
    field.cattle.io/creatorId: user-th54t
    lifecycle.cattle.io/create.mgmt-auth-users-controller: "true"
  finalizers:
  - controller.cattle.io/mgmt-auth-users-controller
  generateName: u-
  generation: 3
  labels:
    cattle.io/creator: norman
  name: test0
password: $2a$10$ozlxua6KD1W2WJxIOMvOX.uBFsubVqiPkivgmwOWz6PhzIoZ3aQKe
spec: {}
username: test0
---

apiVersion: management.cattle.io/v3
kind: Project
metadata:
  annotations:
    authz.management.cattle.io/creator-role-bindings: '{"created":["project-owner"],"required":["project-owner"]}'
    field.cattle.io/creatorId: test0
    lifecycle.cattle.io/create.mgmt-project-rbac-remove: "true"
    lifecycle.cattle.io/create.project-namespace-auth_c-m-9hg7h7h5: "true"
  generateName: p-
  generation: 3
  labels:
    cattle.io/creator: norman
  name: test0
  namespace: c-m-gnvvtdhl
spec:
  clusterName: c-m-gnvvtdhl
  description: ""
  displayName: test0
  enableProjectMonitoring: false
---

administrative: false
apiVersion: management.cattle.io/v3
builtin: false
clusterCreatorDefault: false
context: project
displayName: test0
external: false
hidden: false
kind: RoleTemplate
locked: false
metadata:
  annotations:
    cleanup.cattle.io/rtUpgradeCluster: "true"
    field.cattle.io/creatorId: user-th54t
    lifecycle.cattle.io/create.mgmt-auth-roletemplate-lifecycle: "true"
  finalizers:
  - controller.cattle.io/mgmt-auth-roletemplate-lifecycle
  generateName: rt-
  generation: 3
  labels:
    cattle.io/creator: norman
  name: test0
projectCreatorDefault: false
roleTemplateNames:
- project-member
rules: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    authz.cluster.cattle.io/rtb-owner-updated: p-lsznf_prtb-pz7zw
    cattle.io/creator: norman
    manager: rancher
    operation: Update
  name: rb-test0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test0
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: test0
  
